### ISSUE TITLE
For jobs data directory keeper is not branch aware and count is not configurable on ui

### ISSUE THREAD

**Issue by bariscicek** [Strider-CD/strider-simple-runner#28]
When deploying new builds sometimes it is beneficial to keep job data. As an example when you run a test deployment on test server you want to keep old data files so application keep running even though new builds are deployed. This can be mitigated by increasing count in keeper on jobs init dirs.

However another issue with this is when there are multiple branches one active branch would starve count in keeper, so branch deployment that you want to keep might also be deleted. Here is an example: 

Project with multiple branches: 
master
newFeature
anotherFeature
development 

If count is 4, and if there were one deployment for newFeature, and anotherFeature, having 4 builds in development would destroy builds that you want to keep. 

While development branch having new commits, it is very likely that you are testing newFeature branch and committing there as well. 

Expected working of keeper is to be branch aware and keep 'count' old builds for each branch as users wish.

**Comment by knownasilya** [comment]
Sounds like you are talking about this: https://github.com/Strider-CD/strider-simple-runner/blob/master/lib/index.js#L300
