### ISSUE TITLE
Is this repo still alive?

### ISSUE THREAD

**Issue by dmr** [Strider-CD/strider-simple-runner#36]
A strider Dockerfile I found on google did a `npm i strider-simple-worker` here on my server and there is a `npm@1...` in your package.json which is really old.

--> How do you feel about putting a message in your README explaining that the strider-simple-worker is old?

**Comment by oliversalzburg** [comment]
I don't see what you're referring to regarding the `package.json` and `npm`.

This repo is just as alive as all other Strider repos. We released a new major version of the simple runner in August.

**Comment by dmr** [comment]
Ah, ok. I'm sorry for the confusion.

https://github.com/makethunder/strider-simple-runner points to "npm i strider-simple-worker" and is really old. I accidentally installed that and it broke my installation.
